# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74458b2d565f126376e6b47475f94cb92f285a3fb6b95eb2f12d94f31f0a40e3de92411a9754711c39078f595f8b8b8b0fba2dd31f3e37af2d7b3c19b0eedd26

test:
  secret_key_base: 4a27cd77579c486c01caceda0cabc6f25e2547d6777f5f3df25a91c1a794c4dee0ba0f8a60e768700e6b471e38350bf0163c973f50a49c993b5f358daacd5746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
